"""Tests for scripts/embed_icons.py.

The generator is invoked as a module function (not CLI) so tests can point
at tmp_path layouts. The CLI is a thin shell around :func:`generate_library`.
"""

from __future__ import annotations

import sys
from pathlib import Path

# scripts/ is not a package; import via sys.path
_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT / "scripts"))
import embed_icons  # noqa: E402


def _init_py(list_name: str) -> str:
    """Build a minimal d2/__init__.py fixture with AUTOGEN markers."""
    return (
        "# some unrelated prelude\n"
        f"# BEGIN AUTOGEN:adi\n"
        f"{list_name} = [\n"
        '    "placeholder",\n'
        "]\n"
        f"# END AUTOGEN:adi\n"
        "# more unrelated stuff\n"
    )


def _write_svg(dir_: Path, name: str, body: str = "<svg>X</svg>") -> None:
    (dir_ / f"{name}.svg").write_text(body)


def test_generate_writes_components_d2(tmp_path: Path):
    icons = tmp_path / "icons"
    icons.mkdir()
    _write_svg(icons, "adc", "<svg>ADC</svg>")
    _write_svg(icons, "dac", "<svg>DAC</svg>")

    d2_out = tmp_path / "adi-components.d2"
    init_py = tmp_path / "__init__.py"
    init_py.write_text(_init_py("ADI_COMPONENTS"))

    result = embed_icons.generate_library(
        lib_name="adi",
        list_name="ADI_COMPONENTS",
        order=["adc", "dac"],
        icons_dir=icons,
        d2_output=d2_out,
        init_py=init_py,
        check=False,
    )
    assert result.in_sync is True

    text = d2_out.read_text()
    assert text.startswith("# Auto-generated by scripts/embed_icons.py")
    assert "classes: {" in text
    assert "  adc: {" in text
    assert "  dac: {" in text
    # base64-encoded SVG content must be present
    import base64

    adc_b64 = base64.b64encode(b"<svg>ADC</svg>").decode("ascii")
    assert adc_b64 in text


def test_check_mode_in_sync(tmp_path: Path):
    icons = tmp_path / "icons"
    icons.mkdir()
    _write_svg(icons, "adc", "<svg>A</svg>")

    d2_out = tmp_path / "adi-components.d2"
    init_py = tmp_path / "__init__.py"
    init_py.write_text(_init_py("ADI_COMPONENTS"))

    # First: write
    embed_icons.generate_library(
        lib_name="adi",
        list_name="ADI_COMPONENTS",
        order=["adc"],
        icons_dir=icons,
        d2_output=d2_out,
        init_py=init_py,
        check=False,
    )

    # Now check — must be in sync
    result = embed_icons.generate_library(
        lib_name="adi",
        list_name="ADI_COMPONENTS",
        order=["adc"],
        icons_dir=icons,
        d2_output=d2_out,
        init_py=init_py,
        check=True,
    )
    assert result.in_sync, f"expected in-sync, got diff:\n{result.message}"


def test_check_mode_detects_modified_icon(tmp_path: Path):
    icons = tmp_path / "icons"
    icons.mkdir()
    _write_svg(icons, "adc", "<svg>A</svg>")

    d2_out = tmp_path / "adi-components.d2"
    init_py = tmp_path / "__init__.py"
    init_py.write_text(_init_py("ADI_COMPONENTS"))

    embed_icons.generate_library(
        lib_name="adi",
        list_name="ADI_COMPONENTS",
        order=["adc"],
        icons_dir=icons,
        d2_output=d2_out,
        init_py=init_py,
        check=False,
    )

    # Mutate the icon; check mode should now fail.
    (icons / "adc.svg").write_text("<svg>A-MODIFIED</svg>")
    result = embed_icons.generate_library(
        lib_name="adi",
        list_name="ADI_COMPONENTS",
        order=["adc"],
        icons_dir=icons,
        d2_output=d2_out,
        init_py=init_py,
        check=True,
    )
    assert not result.in_sync
    assert "adi-components.d2" in result.message  # diff header names the file


def test_missing_icon_fails(tmp_path: Path):
    icons = tmp_path / "icons"
    icons.mkdir()
    # Note: "dac" is in order but not on disk.
    _write_svg(icons, "adc", "<svg/>")
    d2_out = tmp_path / "adi-components.d2"
    init_py = tmp_path / "__init__.py"
    init_py.write_text(_init_py("ADI_COMPONENTS"))

    result = embed_icons.generate_library(
        lib_name="adi",
        list_name="ADI_COMPONENTS",
        order=["adc", "dac"],
        icons_dir=icons,
        d2_output=d2_out,
        init_py=init_py,
        check=False,
    )
    assert not result.in_sync
    assert "missing icons" in result.message
    assert "dac" in result.message


def test_orphan_icon_fails(tmp_path: Path):
    icons = tmp_path / "icons"
    icons.mkdir()
    _write_svg(icons, "adc", "<svg/>")
    _write_svg(icons, "zzz-new", "<svg/>")  # not in order
    d2_out = tmp_path / "adi-components.d2"
    init_py = tmp_path / "__init__.py"
    init_py.write_text(_init_py("ADI_COMPONENTS"))

    result = embed_icons.generate_library(
        lib_name="adi",
        list_name="ADI_COMPONENTS",
        order=["adc"],
        icons_dir=icons,
        d2_output=d2_out,
        init_py=init_py,
        check=False,
    )
    assert not result.in_sync
    assert "unknown icons" in result.message
    assert "zzz-new" in result.message
    assert "_ORDER['adi']" in result.message


def test_generator_is_deterministic(tmp_path: Path):
    icons = tmp_path / "icons"
    icons.mkdir()
    _write_svg(icons, "adc", "<svg>X</svg>")
    _write_svg(icons, "dac", "<svg>Y</svg>")

    d2_a = tmp_path / "a.d2"
    d2_b = tmp_path / "b.d2"
    init_a = tmp_path / "init_a.py"
    init_b = tmp_path / "init_b.py"
    init_a.write_text(_init_py("ADI_COMPONENTS"))
    init_b.write_text(_init_py("ADI_COMPONENTS"))

    for d2_out, init_py in ((d2_a, init_a), (d2_b, init_b)):
        embed_icons.generate_library(
            lib_name="adi",
            list_name="ADI_COMPONENTS",
            order=["adc", "dac"],
            icons_dir=icons,
            d2_output=d2_out,
            init_py=init_py,
            check=False,
        )

    assert d2_a.read_text() == d2_b.read_text()
    assert init_a.read_text() == init_b.read_text()
