"""Bindings for the D2 Compiler"""

from __future__ import annotations

import ctypes
import os
import platform
import warnings

__version__ = "0.1.3"

loc = os.path.dirname(os.path.abspath(__file__))

if platform.system() == "Windows":
    lib_path = os.path.join(loc, "resources", "d2lib.lib")
elif platform.system() == "Linux":
    lib_path = os.path.join(loc, "resources", "d2lib.so")
else:
    lib_path = os.path.join(loc, "resources", "d2lib.dylib")

folder_path = os.path.join(loc, "resources")

if not os.path.exists(lib_path):
    if platform.system() == "Windows":
        # Try different extension
        lib_path = os.path.join(loc, "resources", "d2lib.dll")
    if not os.path.exists(lib_path):
        raise FileNotFoundError(f"Could not find {lib_path}")

library = ctypes.cdll.LoadLibrary(lib_path)

_runme = library.runme
_runme.argtypes = [ctypes.c_char_p]
_runme.restype = ctypes.c_char_p

_runme_adi = library.runmeAdi
_runme_adi.argtypes = [ctypes.c_char_p, ctypes.c_char_p]
_runme_adi.restype = ctypes.c_char_p

_runme_lib = library.runmeLib
_runme_lib.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p]
_runme_lib.restype = ctypes.c_char_p

# BEGIN AUTOGEN:adi — regenerated by scripts/embed_icons.py; do not edit by hand
# ADI component class names for reference
ADI_COMPONENTS = [
    "adc",
    "dac",
    "amplifier",
    "filter-lp",
    "filter-bp",
    "filter-hp",
    "pll",
    "mixer",
    "oscillator",
    "comparator",
    "summer",
    "multiplexer",
    "switch",
    "voltage-reference",
    "voltage-regulator",
    "sensor",
    "dsp-fpga",
    "clock",
    "driver",
    "isolator",
    "attenuator",
    "beamformer",
    "axi-interconnect",
    "spi",
    "gpio",
    "i2c",
    "aurora",
    "pfd",
    "charge-pump",
    "loop-filter",
    "vco",
    "divider",
    "ldo",
    "dc-dc-buck",
    "dc-dc-boost",
    "pmic",
    "power-monitor",
    "hot-swap",
    "battery-charger",
    "lna",
    "pa",
    "gain-block",
    "upconverter",
    "downconverter",
    "rf-switch",
    "rf-transceiver",
    "dds",
    "rs485",
    "can",
    "ethernet-phy",
    "lvds",
    "jesd204",
    "inamp",
    "tia",
    "vga",
    "current-sense",
    "clock-buffer",
    "jitter-cleaner",
    "imu",
    "temp-sensor",
    "afe",
    "motor-driver",
    "gate-driver",
    "digipot",
]
# END AUTOGEN:adi

# ADI theme class names for reference
ADI_THEME_CLASSES = [
    "adi-container",
    "adi-signal",
    "adi-signal-analog",
    "adi-signal-digital",
    "adi-signal-clock",
    "adi-signal-power",
    "adi-title",
    "adi-note",
]

# SW (software/AI) component class names for reference — edit by hand;
# SW uses hand-styled classes (not base64-embedded icons) so the embed_icons.py
# generator does not touch this list.
SW_COMPONENTS = [
    "sw-action",
    "sw-agent",
    "sw-api",
    "sw-branch",
    "sw-browser",
    "sw-cache",
    "sw-cloud",
    "sw-config",
    "sw-container-svc",
    "sw-database",
    "sw-dataset",
    "sw-document",
    "sw-eval",
    "sw-function",
    "sw-gateway",
    "sw-log",
    "sw-loop",
    "sw-message",
    "sw-metric",
    "sw-mobile",
    "sw-model",
    "sw-pipeline",
    "sw-prompt",
    "sw-queue",
    "sw-score",
    "sw-server",
    "sw-storage",
    "sw-team",
    "sw-terminal",
    "sw-tool",
    "sw-user",
    "sw-webhook",
]

# SW theme class names for reference
SW_THEME_CLASSES = [
    "sw-container",
    "sw-container-cream",
    "sw-container-green",
    "sw-container-amber",
    "sw-container-red",
    "sw-container-white",
    "sw-step-blue",
    "sw-step-green",
    "sw-step-amber",
    "sw-step-white",
    "sw-title",
    "sw-subtitle",
    "sw-note",
    "sw-flow",
    "sw-flow-data",
    "sw-flow-control",
    "sw-flow-async",
    "sw-flow-error",
    "sw-flow-success",
    "sw-flow-feedback",
    "sw-flow-light",
    "adi-container",
    "adi-signal",
    "adi-signal-analog",
    "adi-signal-digital",
    "adi-signal-clock",
    "adi-signal-power",
    "adi-title",
    "adi-note",
]

JIF_COMPONENTS = [
    "adc",
    "dac",
    "ddc",
    "duc",
    "jesd204framer",
    "jesd204deframer",
    "framer",
    "deframer",
    "input",
    "out_clock_connected",
    "divider",
    "crossbar",
    "mux",
    "shell",
    "ip",
    "phy",
    "transceiver",
    "serdes",
    "decoder",
    "cpll",
    "qpll",
    "trx-dividers",
    "cdr",
    "phase-frequency-detector",
    "charge-pump",
    "loop-filter",
    "vco",
    "voltage-controlled-oscillator",
]

JIF_THEME_CLASSES = [
    "jif-container",
    "jif-signal",
]

_VALID_LIBRARIES = {"adi", "sw", "jif"}


def compile(
    code: str,
    library: str | None = None,
    theme: str = "light",
    adi: bool = False,
) -> str | None:
    """Compile D2 diagram code to SVG.

    Args:
        code: D2 diagram source code.
        library: Component library to include. Either ``"adi"`` for
            Analog Devices signal-chain components, ``"sw"`` for
            software/AI architecture components, ``"jif"`` for
            pyadi-jif block diagrams, or ``None`` for plain D2 compilation.
        theme: Theme variant when a library is used.
            Either ``"light"`` or ``"dark"``.
        adi: Deprecated. Use ``library="adi"`` instead.

    Returns:
        SVG string on success, None on failure.

    Raises:
        RuntimeError: If D2 compilation or rendering fails.
        ValueError: If both *adi* and *library* are set, or if
            *library* is not a recognized name.
    """
    # Handle deprecated adi parameter
    if adi:
        if library is not None:
            raise ValueError(
                "Cannot specify both 'adi=True' and 'library'. Use library='adi' instead."
            )
        warnings.warn(
            "The 'adi' parameter is deprecated. Use library='adi' instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        library = "adi"

    if library is not None and library not in _VALID_LIBRARIES:
        raise ValueError(
            f"Unknown library '{library}'. Expected one of: {sorted(_VALID_LIBRARIES)}"
        )

    try:
        if library is not None:
            graph_bytes = _runme_lib(
                code.encode("utf-8"),
                library.encode("utf-8"),
                theme.encode("utf-8"),
            )
        else:
            graph_bytes = _runme(code.encode("utf-8"))
        result = graph_bytes.decode("utf-8")
        if result.startswith("Error"):
            raise RuntimeError(result)
        return result
    except RuntimeError:
        raise
    except Exception as e:
        print(e)
        return None
