#!/usr/bin/env python3
"""Check SVG files for non-transparent canvas backgrounds.

This is primarily intended for dark-mode documentation assets generated by D2.
"""

from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

RGBA_PATTERN = re.compile(r"rgba?\(([^)]*)\)", re.IGNORECASE)
HSLA_PATTERN = re.compile(r"hsla?\(([^)]*)\)", re.IGNORECASE)
CSS_CLASS_FILL_PATTERN = re.compile(
    r"\.([A-Za-z0-9_-]+)\s*\{[^}]*?\bfill\s*:\s*([^;}\s]+)",
    re.IGNORECASE,
)


def _local_name(tag: str) -> str:
    """Return XML tag name without namespace."""
    if "}" in tag:
        return tag.split("}", 1)[1]
    return tag


def _extract_style_fill(style: str) -> str | None:
    """Extract fill from inline style attribute when present."""
    for part in style.split(";"):
        key, sep, value = part.partition(":")
        if sep and key.strip().lower() == "fill":
            return value.strip()
    return None


def _is_transparent_fill(fill: str) -> bool:
    """Return True when fill value represents full transparency."""
    value = fill.strip().lower()

    if value in {"none", "transparent"}:
        return True

    # #RGBA or #RRGGBBAA
    if value.startswith("#") and len(value) in {5, 9}:
        return value[-1] == "0" if len(value) == 5 else value[-2:] == "00"

    rgba_match = RGBA_PATTERN.fullmatch(value)
    if rgba_match:
        channels = [c.strip() for c in rgba_match.group(1).split(",")]
        if len(channels) == 4:
            try:
                return float(channels[3]) == 0.0
            except ValueError:
                return False
        return False

    hsla_match = HSLA_PATTERN.fullmatch(value)
    if hsla_match:
        channels = [c.strip() for c in hsla_match.group(1).split(",")]
        if len(channels) == 4:
            alpha = channels[3].removesuffix("%")
            try:
                return float(alpha) == 0.0
            except ValueError:
                return False
        return False

    return False


def _find_canvas_rect(root: ET.Element) -> ET.Element | None:
    """Find the first rectangle in the inner SVG node (D2 canvas)."""
    inner_svg = None
    for child in root:
        if _local_name(child.tag) == "svg":
            inner_svg = child
            break

    if inner_svg is None:
        return None

    for child in inner_svg:
        if _local_name(child.tag) == "rect":
            return child

    return None


def _extract_css_class_fills(root: ET.Element) -> dict[str, str]:
    """Extract `.class { fill: ... }` mappings from inline <style> blocks."""
    fills: dict[str, str] = {}
    for node in root.iter():
        if _local_name(node.tag) != "style":
            continue
        css_text = node.text or ""
        for class_name, fill in CSS_CLASS_FILL_PATTERN.findall(css_text):
            fills[class_name.lower()] = fill.strip()
    return fills


def check_svg_text(svg_text: str) -> str | None:
    """Return an issue string if background is invalid, otherwise None."""
    try:
        root = ET.fromstring(svg_text)
    except ET.ParseError as exc:
        return f"invalid SVG XML: {exc}"

    if _local_name(root.tag) != "svg":
        return "root element is not <svg>"

    canvas_rect = _find_canvas_rect(root)
    if canvas_rect is None:
        return "missing canvas rectangle in inner <svg>"

    # Determine effective fill (style attr > class CSS > fill attr)
    style_fill = _extract_style_fill(canvas_rect.attrib.get("style", ""))
    class_fill = None
    class_fills = _extract_css_class_fills(root)
    classes = canvas_rect.attrib.get("class", "").split()
    for cls in classes:
        mapped = class_fills.get(cls.strip().lower())
        if mapped:
            class_fill = mapped
            break
    fill = style_fill or class_fill or canvas_rect.attrib.get("fill")

    if fill is None:
        return "canvas rectangle is missing a fill value"

    if not _is_transparent_fill(fill):
        return f"canvas fill is {fill!r}, expected transparent"

    return None


def check_svg_file(path: Path) -> str | None:
    """Validate one SVG file."""
    try:
        svg_text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return f"unable to read file: {exc}"

    return check_svg_text(svg_text)


def _iter_target_files(targets: list[str], pattern: str) -> list[Path]:
    if not targets:
        return sorted(Path("docs/_static").glob(pattern))

    matched: list[Path] = []
    seen: set[Path] = set()

    for target in targets:
        path = Path(target)
        candidates: list[Path]

        if path.is_file():
            candidates = [path]
        elif path.is_dir():
            candidates = sorted(path.rglob(pattern))
        else:
            candidates = sorted(Path().glob(target))
            if not candidates:
                candidates = [path]

        for candidate in candidates:
            if candidate not in seen:
                seen.add(candidate)
                matched.append(candidate)

    return matched


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Check dark-mode SVG files for non-transparent canvas backgrounds."
    )
    parser.add_argument(
        "targets",
        nargs="*",
        help="Files, directories, or glob patterns. Defaults to docs/_static/*dark*.svg.",
    )
    parser.add_argument(
        "--pattern",
        default="*dark*.svg",
        help="Glob used when a target is a directory (default: *dark*.svg).",
    )
    args = parser.parse_args(argv)

    files = _iter_target_files(args.targets, args.pattern)
    if not files:
        print("No matching SVG files found.")
        return 1

    issues: list[str] = []
    checked_count = 0

    for file_path in files:
        if not file_path.exists():
            issues.append(f"{file_path}: file not found")
            continue
        if file_path.suffix.lower() != ".svg":
            continue

        checked_count += 1
        issue = check_svg_file(file_path)
        if issue:
            issues.append(f"{file_path}: {issue}")

    if issues:
        print("Background issues detected:")
        for issue in issues:
            print(f"- {issue}")
        return 1

    print(f"Checked {checked_count} SVG file(s); all canvas backgrounds are transparent.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
