"""Regenerate lib/<lib>/<lib>-components.d2 and the matching
*_COMPONENTS list in d2/__init__.py from source SVG icons.

Usage:
    python scripts/embed_icons.py --library {adi,sw,all} [--check]

In --check mode nothing is written; the script exits 0 if the
on-disk files already match what would be generated, 1 otherwise
with a unified diff printed to stderr.
"""

from __future__ import annotations

import argparse
import base64
import difflib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent

# Seeded from d2/__init__.py's ADI_COMPONENTS at spec time. When a new ADI
# icon is added (Sub-project 2), append its class name here explicitly.
_ADI_ORDER: list[str] = [
    "adc", "dac", "amplifier", "filter-lp", "filter-bp", "filter-hp", "pll",
    "mixer", "oscillator", "comparator", "summer", "multiplexer", "switch",
    "voltage-reference", "voltage-regulator", "sensor", "dsp-fpga", "clock",
    "driver", "isolator", "attenuator", "beamformer", "axi-interconnect",
    "spi", "gpio", "i2c", "aurora", "pfd", "charge-pump", "loop-filter",
    "vco", "divider", "ldo", "dc-dc-buck", "dc-dc-boost", "pmic",
    "power-monitor", "hot-swap", "battery-charger", "lna", "pa", "gain-block",
    "upconverter", "downconverter", "rf-switch", "rf-transceiver", "dds",
    "rs485", "can", "ethernet-phy", "lvds", "jesd204", "inamp", "tia", "vga",
    "current-sense", "clock-buffer", "jitter-cleaner", "imu", "temp-sensor",
    "afe", "motor-driver", "gate-driver", "digipot",
]


@dataclass
class GenerateResult:
    in_sync: bool
    message: str = ""


def _render_d2(lib_name: str, order: list[str], icons_dir: Path) -> str:
    lines = [
        "# Auto-generated by scripts/embed_icons.py — do not edit manually",
        f"# Regenerate with: python scripts/embed_icons.py --library {lib_name}",
        "",
        "classes: {",
    ]
    for name in order:
        svg = (icons_dir / f"{name}.svg").read_bytes()
        b64 = base64.b64encode(svg).decode("ascii")
        lines.append(f"  {name}: {{")
        lines.append(f'    icon: "data:image/svg+xml;base64,{b64}"')
        lines.append("  }")
    lines.append("}")
    lines.append("")  # trailing newline
    return "\n".join(lines)


def _render_list(list_name: str, order: list[str]) -> str:
    body = [f"{list_name} = ["]
    for name in order:
        body.append(f'    "{name}",')
    body.append("]")
    return "\n".join(body)


_MARKER_RE = re.compile(
    r"(# BEGIN AUTOGEN:(?P<lib>[a-z]+)[^\n]*\n)(.*?)(# END AUTOGEN:(?P=lib)\n)",
    re.DOTALL,
)


def _rewrite_init_block(init_text: str, lib_name: str, new_body: str) -> str:
    def _repl(match: re.Match[str]) -> str:
        if match.group("lib") != lib_name:
            return match.group(0)
        # Preserve the original list-description comment (the line between BEGIN marker
        # and the list declaration): find it inside the current block, keep it as-is.
        original_body = match.group(3)
        comment_match = re.match(
            r"(# [A-Z][^\n]*\n)",
            original_body.lstrip("\n"),
        )
        description = comment_match.group(1) if comment_match else ""
        return f"{match.group(1)}{description}{new_body}\n{match.group(4)}"

    replaced, n = _MARKER_RE.subn(_repl, init_text)
    if n == 0:
        raise ValueError(f"no BEGIN AUTOGEN:{lib_name} marker found in init file")
    return replaced


def generate_library(
    *,
    lib_name: str,
    list_name: str,
    order: list[str],
    icons_dir: Path,
    d2_output: Path,
    init_py: Path,
    check: bool,
) -> GenerateResult:
    # Validate sources first
    missing = [n for n in order if not (icons_dir / f"{n}.svg").is_file()]
    if missing:
        return GenerateResult(False, f"missing icons in {icons_dir}: {missing}")
    on_disk = {p.stem for p in icons_dir.glob("*.svg")}
    orphans = sorted(on_disk - set(order))
    if orphans:
        return GenerateResult(
            False,
            f"unknown icons in {icons_dir}: {orphans} — add to _ORDER['{lib_name}']",
        )

    new_d2 = _render_d2(lib_name, order, icons_dir)
    new_list = _render_list(list_name, order)

    current_init = init_py.read_text()
    new_init = _rewrite_init_block(current_init, lib_name, new_list)

    if check:
        d2_diff = _diff(d2_output, new_d2)
        init_diff = _diff(init_py, new_init)
        if d2_diff or init_diff:
            return GenerateResult(False, d2_diff + init_diff)
        return GenerateResult(True)
    d2_output.write_text(new_d2)
    init_py.write_text(new_init)
    return GenerateResult(True)


def _diff(existing: Path, generated: str) -> str:
    current = existing.read_text() if existing.exists() else ""
    if current == generated:
        return ""
    return "".join(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=f"a/{existing.name}",
            tofile=f"b/{existing.name} (generated)",
        )
    )


def _main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--library", choices=["adi", "sw", "all"], required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    libs = ["adi", "sw"] if args.library == "all" else [args.library]
    exit_code = 0
    for lib in libs:
        if lib == "adi":
            order = _ADI_ORDER
            list_name = "ADI_COMPONENTS"
        else:
            order = sorted(
                p.stem for p in (_ROOT / "lib" / "sw" / "icons").glob("*.svg")
            )
            list_name = "SW_COMPONENTS"
        result = generate_library(
            lib_name=lib,
            list_name=list_name,
            order=order,
            icons_dir=_ROOT / "lib" / lib / "icons",
            d2_output=_ROOT / "lib" / lib / f"{lib}-components.d2",
            init_py=_ROOT / "d2" / "__init__.py",
            check=args.check,
        )
        if not result.in_sync:
            print(result.message, file=sys.stderr)
            exit_code = 1
    return exit_code


if __name__ == "__main__":
    sys.exit(_main())
