#!/usr/bin/env bash
# Generate lib/sw/sw-components.d2 from SVG source files in lib/sw/icons/
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ICONS_DIR="$SCRIPT_DIR/../lib/sw/icons"
OUTPUT="$SCRIPT_DIR/../lib/sw/sw-components.d2"

echo "# Auto-generated by scripts/embed-sw-icons.sh — do not edit manually" > "$OUTPUT"
echo "# Regenerate with: bash scripts/embed-sw-icons.sh" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "classes: {" >> "$OUTPUT"

for svg in "$ICONS_DIR"/sw-*.svg; do
    name=$(basename "$svg" .svg)
    b64=$(base64 -w0 "$svg" 2>/dev/null || base64 -i "$svg" 2>/dev/null)
    cat >> "$OUTPUT" <<EOF
  ${name}: {
    shape: image
    icon: "data:image/svg+xml;base64,${b64}"
    width: 100
    height: 70
  }
EOF
done

echo "}" >> "$OUTPUT"

echo "Generated $OUTPUT with $(grep -c 'shape: image' "$OUTPUT") components"
