name: Checks

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  embed_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install nox
        run: pip install nox uv
      - name: Run embed_check
        run: nox -s embed_check
